# Site settings
title:       Rinat Khanov
email:       rinat@khanov.com
author:      Rinat Khanov
description: "Rinat Khanov on technology and life."
baseurl:     ""
url:         "http://blog.rinatkhanov.me"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username:
stackoverflow_id:
twitter_username: rinatkhanov
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     10
sass:
  compressed: true
gems:
  - jekyll-sitemap
